### ISSUE TITLE
Feature Request: campus-make-partition-region

### ISSUE THREAD

**Issue by jgarte** [eshrh/campus-emacs#2]
Hi, 

WDYT if we had a function called `campus-make-partition-region` that would allow the following workflow?

Select region:

![image](https://github.com/eshrh/campus-emacs/assets/47760695/7afa2d49-46c0-4aa1-8101-39b66f635090)

Call `campus-make-partition-region`:

![image](https://github.com/eshrh/campus-emacs/assets/47760695/dd9dff67-a600-433e-b455-28c61fd122ec)

**Comment by eshrh** [comment]
Great idea! just implemented it.
